### ISSUE TITLE
Is there any 32bit version for DIV/SQRT operation?

### ISSUE THREAD

**Issue by ShawnLess** [ucb-bar/berkeley-hardfloat#11]
I want to implement the 'F' extension of RISC-V ISA based on berkeley-hardfloat, everything is great except I couldn't find a 32bit implementation for DIV/SQRT yet. I'm wondering how to implement the 32bit DIV/SQRT based on this repo.

**Comment by jhauser-ucberkeley** [comment]
Please be aware that the current version of Berkeley HardFloat is still preliminary and largely unsupported.
That said, you can up-convert your 32-bit floating-point inputs to 64 bits, then use 'DivSqrtRecF64ToRaw_mulAddZ31' to create a 64-bit-compatible "raw" output, and lastly round to the 32-bit format.  With the recoded format used by Berkeley HardFloat, up-conversions done by 'RecFNToRecFN(8, 24, 11, 53)' are extremely cheap.  The rounding of the 64-bit-compatible "raw" result can be done either by 'RoundAnyRawFNToRecFN(11, 55, 8, 24, __)' or by 'resizeRawFN(8, 26, x)' followed by 'RoundRawFNToRecFN(8, 24, __)'.  If you don't know what options to fill in for "__", 0 is always safe.

**Comment by jhauser-ucberkeley** [comment]
GitHub converted my underscore characters to bold font on this Web page.  If that makes it harder to read my response, you can always try complaining to the brainless robot (and see how far it gets you).

**Comment by ShawnLess** [comment]
Thanks for the answer, John. 
I saw that the rocket chip had implemented the single precision DIV/SQRT in the same way as you said.  This would solve the problem but because of the limited chip area,  we couldn't support 64bit floating point operation yet. 

An open source hardfloat is really helpful for the open source chip ecosystem and I hope we could keep on improving it.
