### ISSUE TITLE
Question about arbitrary precision support

### ISSUE THREAD

**Issue by noureddine-as** [ucb-bar/berkeley-hardfloat#32]
Hello,

I am studying the FPU module of Rocket Chip SoC Generator, which uses this library. I also see that all the modules here are configurable (using `expWidth: Int, sigWidth: Int`). Those values are then set in Rocket Chip as `(8, 24)` for single precision and `(11, 53)` for double precision.

My 1st question is, is this library valid also for IEEE non-standard arbitrary bit-widths? E.g. expWidth = 6, sigWidth = 18 ?
What about the IEEE half-precision standard?

Thank you!
Best regards,

**Comment by aswaterman** [comment]
This library hasn't been verified for sizes other than the IEEE ones, but we generally expect that it will work for other sizes, under some constraints.  For example, if `2^expWidth` falls below `sigWidth + some constant I'm not totally sure of`, it will not work.

**Comment by noureddine-as** [comment]
Thank you for the answer @aswaterman . Is there any documentation on those requirements? I saw two `require` statements in the `FPU.scala` but not sure if there are any other dependencies/assumptions that aren't mentioned?

Just another question more related to Rocket Chip FPU implementation than this library, the `FPU.scala`is designed in a way that the F and D extensions are both included when an RV64 is equipped with FPU. I'm wondering if it's possible (and if it makes sense) for me to make it take only the **F** or only the **D** for example? e.g. to construct a RV64IMA**F**C (or RV64IMA**D**C) instead of RV64IMA**FD**C

Thanks,
Best regards.

**Comment by aswaterman** [comment]
Sorry, probably no documentation.

F-only is supported. D-only is not supported (it’s not allowed by the ISA).

**Comment by noureddine-as** [comment]
Okay, thanks for these informations @aswaterman.

**Comment by aswaterman** [comment]
You're welcome!
