### ISSUE TITLE
compilation error

### ISSUE THREAD

**Issue by shi27feng** [ucb-bar/berkeley-hardfloat#43]
Hi,
Does anyone know how to solve the error below? Thanks a lot!

[info] Reapplying settings...
[info] Set current project to chaos (in build file:/C:/Workspace/.../)
[IJ]sbt:project> compile
[info] Compiling 40 Scala sources to C:\Workspace\...\scala-2.12\classes ...
[error] C:\Workspace\...\src\main\scala\hardfload\primitives.scala:92:52: value asBools is not a member of Chisel.UInt
[error]     def apply(in: UInt): UInt = PriorityEncoder(in.asBools.reverse)
[error]                                                    ^
[error] one error found
[error] (Compile / compileIncremental) Compilation failed
[error] Total time: 10 s, completed Mar 30, 2020, 6:00:00 PM
[IJ]sbt:project>

**Comment by edwardcwang** [comment]
Hello, do you get the same error with a fresh checkout of the repo?

**Comment by shi27feng** [comment]
Thank you for the prompt reply. 
I'll try to compile it separately

**Comment by shi27feng** [comment]
Problem solved.
My chisel is too old (3.1), after having been updated, everything passes the compilation.
what I changed in "build.sbt":
val defaultVersions = Map(
  "chisel3" -> "3.2.4",
  "chisel-iotesters" -> "1.3.4",
  "firrtl" -> "1.2.4",
  "firrtl-interpreter" -> "1.2.4",
  "treadle" -> "1.1.4"
)

**Comment by edwardcwang** [comment]
Glad to hear you were able to resolve it!
