### ISSUE TITLE
dependencies issue

### ISSUE THREAD

**Issue by dzwduan** [ucb-bar/berkeley-hardfloat#79]
sbt.librarymanagement.ResolveException: Error downloading edu.berkeley.cs:hardfloat_2.13:1.5-SNAPSHOT.

but in https://repo1.maven.org/maven2/edu/berkeley/cs/ only found hardfloat_2.12

**Comment by FJShen** [comment]
I'm having similar issues with Scala version compatibility. I'm trying to build a Chisel project from the latest official chisel-template and import the HardFloat library, but the Scala versions of them aren't compatible. Apologies if my question look naive, but I'm quite a novice to the Scala - Maven world (my background leans more on the C/C++ side of programming langauges).

The current chisel-template requires Scala 2.13.8 [(build.sbt)](https://github.com/freechipsproject/chisel-template/blob/d7a5dd8ee7a3255cce8d5636900e1dea5b51fe1d/build.sbt), but so far I've only found 2.12-compatible releases of HardFloat on the Maven Repository [hardfloat_2.12](https://central.sonatype.com/artifact/edu.berkeley.cs/hardfloat_2.12/1.2.4). 

What options do I have if I want to import HardFloat into a Scala 2.13 project?

**Comment by sequencer** [comment]
you can try to use mill to publish local or build hardfloat from source.

**Comment by FJShen** [comment]
For now I'm copying the "hardfloat" directory into my Chisel project directory like this: `<project_root>/external/hardfloat` and adding this line to my build.sbt file: `Compile / unmanagedSourceDirectories += baseDirectory.value / "external/hardfloat/src"`. The SBT compilation went fine.

**Comment by dzwduan** [comment]
I also sovled by this
